/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfileData = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'handle' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const PostInput = IDL.Record({
  'media' : IDL.Opt(ExternalBlob),
  'authorName' : IDL.Text,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'media' : IDL.Opt(ExternalBlob),
  'likeCount' : IDL.Nat,
  'authorName' : IDL.Text,
  'viewCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
  'authorPrincipal' : IDL.Principal,
  'postId' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'participants' : IDL.Tuple(IDL.Principal, IDL.Principal),
  'lastUpdated' : IDL.Int,
});
export const FriendshipStatusEnum = IDL.Variant({
  'notConnected' : IDL.Null,
  'pendingOutgoing' : IDL.Null,
  'friends' : IDL.Null,
  'pendingIncoming' : IDL.Null,
});
export const FriendRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const FriendRequest = IDL.Record({
  'status' : FriendRequestStatus,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'postId' : IDL.Opt(IDL.Nat),
});
export const NotificationType = IDL.Variant({
  'comment' : IDL.Null,
  'message' : IDL.Null,
  'new_shadow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notificationType' : NotificationType,
  'read' : IDL.Bool,
  'fromPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'postId' : IDL.Opt(IDL.Nat),
});
export const UserProfileSummary = IDL.Record({
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(ExternalBlob),
  'followerCount' : IDL.Nat,
  'handle' : IDL.Text,
  'followingCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfileData], [], []),
  'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileData)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFriendsList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFriendshipStatus' : IDL.Func(
      [IDL.Principal],
      [FriendshipStatusEnum],
      ['query'],
    ),
  'getIncomingFriendRequests' : IDL.Func(
      [],
      [IDL.Vec(FriendRequest)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOutgoingFriendRequests' : IDL.Func(
      [],
      [IDL.Vec(FriendRequest)],
      ['query'],
    ),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getProfileByHandle' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfileData)],
      ['query'],
    ),
  'getProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileData)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'recordView' : IDL.Func([IDL.Nat], [], []),
  'respondToFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileData], [], []),
  'searchHandles' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfileSummary)], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unfriend' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfileData = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'handle' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const PostInput = IDL.Record({
    'media' : IDL.Opt(ExternalBlob),
    'authorName' : IDL.Text,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'media' : IDL.Opt(ExternalBlob),
    'likeCount' : IDL.Nat,
    'authorName' : IDL.Text,
    'viewCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
    'authorPrincipal' : IDL.Principal,
    'postId' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'participants' : IDL.Tuple(IDL.Principal, IDL.Principal),
    'lastUpdated' : IDL.Int,
  });
  const FriendshipStatusEnum = IDL.Variant({
    'notConnected' : IDL.Null,
    'pendingOutgoing' : IDL.Null,
    'friends' : IDL.Null,
    'pendingIncoming' : IDL.Null,
  });
  const FriendRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const FriendRequest = IDL.Record({
    'status' : FriendRequestStatus,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'postId' : IDL.Opt(IDL.Nat),
  });
  const NotificationType = IDL.Variant({
    'comment' : IDL.Null,
    'message' : IDL.Null,
    'new_shadow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notificationType' : NotificationType,
    'read' : IDL.Bool,
    'fromPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'postId' : IDL.Opt(IDL.Nat),
  });
  const UserProfileSummary = IDL.Record({
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(ExternalBlob),
    'followerCount' : IDL.Nat,
    'handle' : IDL.Text,
    'followingCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfileData], [], []),
    'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileData)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFriendsList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFriendshipStatus' : IDL.Func(
        [IDL.Principal],
        [FriendshipStatusEnum],
        ['query'],
      ),
    'getIncomingFriendRequests' : IDL.Func(
        [],
        [IDL.Vec(FriendRequest)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOutgoingFriendRequests' : IDL.Func(
        [],
        [IDL.Vec(FriendRequest)],
        ['query'],
      ),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getProfileByHandle' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfileData)],
        ['query'],
      ),
    'getProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileData)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'recordView' : IDL.Func([IDL.Nat], [], []),
    'respondToFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileData], [], []),
    'searchHandles' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfileSummary)], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unfriend' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };