/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfileData = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'handle' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const PostInput = IDL.Record({
  'media' : IDL.Opt(ExternalBlob),
  'authorName' : IDL.Text,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'media' : IDL.Opt(ExternalBlob),
  'likeCount' : IDL.Nat,
  'authorName' : IDL.Text,
  'viewCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
  'authorPrincipal' : IDL.Principal,
  'postId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfileData], [], []),
  'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileData)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getProfileByHandle' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfileData)],
      ['query'],
    ),
  'getProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileData)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'recordView' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileData], [], []),
  'searchHandles' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfileData = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'handle' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const PostInput = IDL.Record({
    'media' : IDL.Opt(ExternalBlob),
    'authorName' : IDL.Text,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'media' : IDL.Opt(ExternalBlob),
    'likeCount' : IDL.Nat,
    'authorName' : IDL.Text,
    'viewCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
    'authorPrincipal' : IDL.Principal,
    'postId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfileData], [], []),
    'createPost' : IDL.Func([PostInput], [IDL.Nat], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileData)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getProfileByHandle' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfileData)],
        ['query'],
      ),
    'getProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileData)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'recordView' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileData], [], []),
    'searchHandles' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };