/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'text' : string,
  'authorName' : string,
  'timestamp' : bigint,
  'authorPrincipal' : Principal,
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Post {
  'id' : bigint,
  'media' : [] | [ExternalBlob],
  'likeCount' : bigint,
  'authorName' : string,
  'viewCount' : bigint,
  'timestamp' : bigint,
  'caption' : string,
  'mediaType' : string,
  'authorPrincipal' : Principal,
}
export interface PostInput {
  'media' : [] | [ExternalBlob],
  'authorName' : string,
  'caption' : string,
  'mediaType' : string,
}
export interface UserProfileData {
  'bio' : string,
  'displayName' : string,
  'handle' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfileData], undefined>,
  'createPost' : ActorMethod<[PostInput], bigint>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileData]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getProfileByHandle' : ActorMethod<[string], [] | [UserProfileData]>,
  'getProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfileData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileData]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'recordView' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileData], undefined>,
  'searchHandles' : ActorMethod<[string], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];