/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'text' : string,
  'authorName' : string,
  'timestamp' : bigint,
  'authorPrincipal' : Principal,
  'postId' : bigint,
}
export interface Conversation {
  'participants' : [Principal, Principal],
  'lastUpdated' : bigint,
}
export interface CreatorRanking {
  'principal' : Principal,
  'username' : string,
  'profilePicBlob' : [] | [ExternalBlob],
  'followerCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'read' : boolean,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : bigint,
  'postId' : [] | [bigint],
}
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'read' : boolean,
  'fromPrincipal' : Principal,
  'timestamp' : bigint,
  'postId' : [] | [bigint],
}
export type NotificationType = { 'comment' : null } |
  { 'message' : null } |
  { 'new_shadow' : null };
export interface Post {
  'id' : bigint,
  'media' : [] | [ExternalBlob],
  'likeCount' : bigint,
  'authorName' : string,
  'viewCount' : bigint,
  'timestamp' : bigint,
  'caption' : string,
  'mediaType' : string,
  'authorPrincipal' : Principal,
}
export interface PostInput {
  'media' : [] | [ExternalBlob],
  'authorName' : string,
  'caption' : string,
  'mediaType' : string,
}
export interface UserProfileData {
  'bio' : string,
  'displayName' : string,
  'handle' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfileData], undefined>,
  'createPost' : ActorMethod<[PostInput], bigint>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileData]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getLatestPostByUser' : ActorMethod<[Principal], [] | [Post]>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getProfileByHandle' : ActorMethod<[string], [] | [UserProfileData]>,
  'getProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfileData]>,
  'getProfileRowUsers' : ActorMethod<[], Array<Principal>>,
  'getTopCreatorsByShadows' : ActorMethod<[bigint], Array<CreatorRanking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileData]>,
  'getVisitHistory' : ActorMethod<[], Array<Principal>>,
  'hasNewPostSince' : ActorMethod<[Principal, bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markMessagesRead' : ActorMethod<[Principal], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'recordView' : ActorMethod<[bigint], undefined>,
  'recordVisit' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileData], undefined>,
  'searchHandles' : ActorMethod<[string], Array<string>>,
  'sendMessage' : ActorMethod<[Principal, string, [] | [bigint]], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];